diff --git a/Makefile b/Makefile
index ac9d1a4..54469fa 100644
--- a/Makefile
+++ b/Makefile
@@ -10,7 +10,7 @@ getoptdir=$(sharedir)/getopt
 localedir=$(sharedir)/locale
 
 # Define this to 0 to use the getopt(3) routines in this package.
-LIBCGETOPT=1
+LIBCGETOPT=0
 
 # Define this to 1 if you do not have the gettext routines
 WITHOUT_GETTEXT=0
@@ -32,9 +32,9 @@ MSGFMT=msgfmt
 LANGUAGES = ca cs da de es et eu fi fr gl hr hu id it ja nl pl pt_BR ru sl sv tr uk vi zh_CN zh_TW
 MOFILES:=$(patsubst %,po/%.mo,$(LANGUAGES))
 
-CPPFLAGS=-DLIBCGETOPT=$(LIBCGETOPT) -DWITHOUT_GETTEXT=$(WITHOUT_GETTEXT) -DLOCALEDIR=\"$(localedir)\" -DNOT_UTIL_LINUX -Dprogram_invocation_short_name=\"$(PACKAGE)\"  -Dprogram_version=\"$(VERSION)\"
+override CPPFLAGS+=-DLIBCGETOPT=$(LIBCGETOPT) -DWITHOUT_GETTEXT=$(WITHOUT_GETTEXT) -DLOCALEDIR=\"$(localedir)\" -DNOT_UTIL_LINUX -Dprogram_invocation_short_name=\"$(PACKAGE)\"  -Dprogram_version=\"$(VERSION)\"
 ifeq ($(LIBCGETOPT),0)
-CPPFLAGS+=-I./gnu 
+override CPPFLAGS+=-I./gnu 
 endif
 WARNINGS=-Wall \
          -W -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual \
