diff --git a/Makefile b/Makefile
index ac9d1a4..62312fb 100644
--- a/Makefile
+++ b/Makefile
@@ -8,9 +8,11 @@ man1dir=$(mandir)/man1
 sharedir=$(prefix)/share
 getoptdir=$(sharedir)/getopt
 localedir=$(sharedir)/locale
+libdir=$(prefix)/lib
+includedir=$(prefix)/include
 
 # Define this to 0 to use the getopt(3) routines in this package.
-LIBCGETOPT=1
+LIBCGETOPT=0
 
 # Define this to 1 if you do not have the gettext routines
 WITHOUT_GETTEXT=0
@@ -28,13 +30,14 @@ LD=ld
 RM=rm -f
 INSTALL=install
 MSGFMT=msgfmt
+AR=ar
 
 LANGUAGES = ca cs da de es et eu fi fr gl hr hu id it ja nl pl pt_BR ru sl sv tr uk vi zh_CN zh_TW
 MOFILES:=$(patsubst %,po/%.mo,$(LANGUAGES))
 
-CPPFLAGS=-DLIBCGETOPT=$(LIBCGETOPT) -DWITHOUT_GETTEXT=$(WITHOUT_GETTEXT) -DLOCALEDIR=\"$(localedir)\" -DNOT_UTIL_LINUX -Dprogram_invocation_short_name=\"$(PACKAGE)\"  -Dprogram_version=\"$(VERSION)\"
+override CPPFLAGS+=-DLIBCGETOPT=$(LIBCGETOPT) -DWITHOUT_GETTEXT=$(WITHOUT_GETTEXT) -DLOCALEDIR=\"$(localedir)\" -DNOT_UTIL_LINUX -Dprogram_invocation_short_name=\"$(PACKAGE)\"  -Dprogram_version=\"$(VERSION)\"
 ifeq ($(LIBCGETOPT),0)
-CPPFLAGS+=-I./gnu 
+override CPPFLAGS+=-I./gnu 
 endif
 WARNINGS=-Wall \
          -W -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual \
@@ -54,19 +57,27 @@ objects=$(sources:.c=.o)
 
 binaries=getopt
 
+archive_target=libgetopt.a
+archive_objects=$(objects)
+
+$(archive_target):	$(archive_objects)
+		$(AR) rcs $@ $(filter gnu/%,$(objects)) 
+
 .PHONY: all clean realclean 
-all: $(binaries) all_po
+all: $(binaries) $(archive_target) all_po
 
 clean: clean_po
-	-$(RM) $(objects) $(binaries) 
+	-$(RM) $(objects) $(binaries) $(archive_target)
 
 getopt: $(objects)
-	$(CC) $(LDFLAGS) -o $@ $(objects)
+	$(CC) $(LDFLAGS) -o $@ $(objects) $(LIBS)
 
 install: getopt install_po
-	$(INSTALL) -m 755 -d $(DESTDIR)$(bindir) $(DESTDIR)$(man1dir)
+	$(INSTALL) -m 755 -d $(DESTDIR)$(bindir) $(DESTDIR)$(man1dir) $(DESTDIR)$(libdir) $(DESTDIR)$(includedir)
 	$(INSTALL) -m 755 getopt $(DESTDIR)$(bindir)
 	$(INSTALL) -m 644 getopt.1 $(DESTDIR)$(man1dir)
+	$(INSTALL) -m 644 libgetopt.a $(DESTDIR)$(libdir)
+	$(INSTALL) -m 644 gnu/getopt.h $(DESTDIR)$(includedir)
 
 install_doc:
 	$(INSTALL) -m 755 -d $(DESTDIR)$(getoptdir)
diff --git a/Makefile.util-linux b/Makefile.util-linux
index a8a8e9d..2680473 100644
--- a/Makefile.util-linux
+++ b/Makefile.util-linux
@@ -44,7 +44,7 @@ clean:
 	-$(RM) $(OBJECTS) $(BINARIES) 
 
 getopt: $(OBJECTS)
-	$(CC) $(LDFLAGS) $< -o $@
+	$(CC) $(LDFLAGS) $< -o $@ $(LIBS)
 
 install: getopt
 	$(INSTALLDIR) $(USRBINDIR) $(MAN1DIR) $(GETOPTDIR)
